export const DEFAULT_SETTINGS = {
  general: {
    startOnBoot: true,
    minimizeToTray: true,
    startHidden: true,
    autoCleanOnCopy: true,
    hasSeenOnboarding: false,
    language: "id",
    theme: "system",
    enableContextMenu: true,
    contextMenuMode: "top_level",
  },
  hotkeys: {
    pasteClean: "Alt+Shift+V",
    ocrCapture: "Ctrl+Alt+S",
    screenshotCapture: "Shift+PrintScreen",
    presetSwitch: "Ctrl+Alt+P",
    ghostWrite: "Ctrl+Alt+G",
    translateClipboard: "Ctrl+Alt+T",
    multiCopy: "CmdOrCtrl+Alt+C",
    queueToggle: "CmdOrCtrl+Alt+Q",
    historyOpen: "CmdOrCtrl+Alt+H",
    commandPalette: "CmdOrCtrl+Alt+K",
    undoLastPaste: "CmdOrCtrl+Alt+Z",
  },
  presets: {
    active: "keepStructure",
    custom: [],
  },
  security: {
    detectSensitive: true,
    autoClear: false,
    clearTimerSeconds: 30,
    maskMode: "smart",
    unknownContextAction: "warn",
  },
  history: {
    enabled: true,
    maxItems: 100,
    retentionDays: 30,
  },
  ai: {
    enabled: false,
    provider: "local",
    apiKey: "",
    baseUrl: "",
    model: "",
    autoDetect: true,
    aiMode: "auto",
  },
  ocr: {
    languages: ["ind", "eng"],
    autoClean: true,
  },
  sync: {
    enabled: false,
    deviceId: "",
    pairedDevices: [],
  },
  appFilter: { mode: "off", apps: [] },
  automation: {
    trustModeDefault: "balanced",
    appTrustModes: [],
    enableUniversalFallback: true,
    enablePastePreview: true,
    previewHoldMs: 250,
    enableCommandPalette: true,
    enableIntentFieldDetection: true,
    enableSmartUrlTransform: true,
    enableLocaleAwareness: true,
    enableHealthGuard: true,
    enableAutoLearning: true,
    enableRecipes: true,
    enableUndo: true,
    sessionClusterMinutes: 20,
    paletteFavorites: [],
  },
  privacy: {
    enableEphemeralSensitiveClips: true,
    sensitiveTtlSeconds: 90,
    sensitiveAllowlistApps: [],
    enablePrivacyFirewall: true,
    firewallRedactionMode: "display_only",
    autoMutateOnPublicApps: false,
    mutateClipboardApps: [],
    neverPersistSensitive: true,
  },
  diagnostics: {
    observabilityEnabled: false, // default OFF — user must opt-in
    maxEvents: 500,
    telemetryDeviceId: "",
  },
  recipes: [],
  autoLearnedRules: [],
} as const;

export const RECOMMENDED_PASTE_HOTKEYS = [
  "Ctrl+Shift+V",
  "Alt+Shift+V",
  "CmdOrCtrl+Alt+Space",
  "CmdOrCtrl+Shift+Space",
  "CmdOrCtrl+Alt+F8",
  "CmdOrCtrl+Shift+F8",
] as const;

export const RECOMMENDED_SCREENSHOT_HOTKEYS = [
  "Shift+PrintScreen",
  "Ctrl+Shift+PrintScreen",
  "CmdOrCtrl+Shift+S",
  "CmdOrCtrl+Alt+Shift+S",
] as const;
