import { contextBridge, ipcRenderer } from "electron";

const ALLOWED_CHANNELS = new Set<string>([
  "ai:rewrite",
  "ai:test-connection",
  "ai:detect-tone",
  "ai:summarize-url",
  "ai:usage-stats",
  "ai:clear-usage",
  "chart:generate",
  "clipboard:write",
  "clipboard:paste",
  "clipboard:detect",
  "clipboard:ghost-write",
  "clipboard:redact",
  "clipper:clip-url",
  "clipper:to-markdown",
  "clipper:to-plaintext",
  "dragdrop:get-items",
  "dragdrop:add-item",
  "dragdrop:reorder",
  "dragdrop:combine",
  "dragdrop:clear",
  "history:list",
  "history:pin",
  "history:delete",
  "history:update",
  "history:delete-many",
  "history:clear",
  "history:restore",
  "history:export",
  "ocr:recognize",
  "queue:enqueue",
  "queue:dequeue",
  "queue:peek",
  "queue:size",
  "queue:clear",
  "multi:start",
  "multi:add",
  "multi:merge",
  "multi:clear",
  "multi:state",
  "qr:generate",
  "ring:get-items",
  "ring:search",
  "ring:select",
  "ring:select-original",
  "ring:delete",
  "ring:pin",
  "security:mask",
  "security:scan",
  "settings:get",
  "settings:update",
  "settings:get-app-profiles",
  "settings:context-rules:list",
  "settings:context-rules:create",
  "settings:context-rules:update",
  "settings:context-rules:delete",
  "settings:context-menu-status",
  "settings:context-menu-repair",
  "settings:set-app-profile",
  "settings:set-trust-mode",
  "settings:export-portable",
  "settings:import-portable",
  "diagnostics:observability",
  "diagnostics:fallback-methods",
  "timeline:clusters",
  "automation:set-active-preset",
  "automation:paste-feedback",
  "automation:feedback-action",
  "system:running-apps",
  "snippet:list",
  "snippet:create",
  "snippet:update",
  "snippet:delete",
  "snippet:expand",
  "template:fill",
  "template:list",
  "template:create",
  "template:update",
  "template:delete",
  "transform:convert-format",
  "transform:math",
  "transform:color",
  "transform:md-to-rtf",
  "transform:open-links",
  "transform:extract-file",
  "transform:scrape-url",
  "transform:make-secret",
  "transform:case-convert",
  "transform:translate",
  "usage:summary",
  "window:open",
]);

const ALLOWED_ON_CHANNELS = new Set<string>([
  "security:policy",
  "security:alert",
  "clipboard:cleaned",
  "clipboard:auto-cleared",
  "clipboard:content",
  "ocr:result",
  "snippet:auto-created",
  "sync:connected",
  "sync:disconnected",
  "sync:received",
  "toast:data",
]);

contextBridge.exposeInMainWorld("smartpaste", {
  invoke: (channel: string, payload?: unknown) => {
    if (!ALLOWED_CHANNELS.has(channel)) {
      throw new Error(`Blocked IPC invoke channel: ${channel}`);
    }
    return ipcRenderer.invoke(channel, payload);
  },
  on: (
    channel: string,
    listener: (event: Electron.IpcRendererEvent, payload: unknown) => void,
  ) => {
    if (!ALLOWED_ON_CHANNELS.has(channel)) {
      throw new Error(`Blocked IPC event channel: ${channel}`);
    }
    ipcRenderer.on(channel, listener);
    return () => {
      ipcRenderer.removeListener(channel, listener);
    };
  },
});
